# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reserve.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reserve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreserve.proto\x12\x10protos.warehouse\"D\n\x04Item\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07instock\x18\x03 \x01(\r\x12\x0f\n\x07reserve\x18\x04 \x01(\r\"4\n\x12ReserveItemRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\r\"\x84\x01\n\x13ReserveItemResponse\x12G\n\x10notificationType\x18\x01 \x01(\x0e\x32-.protos.warehouse.ReserveNotificationTypeEnum\x12$\n\x04item\x18\x02 \x01(\x0b\x32\x16.protos.warehouse.Item*t\n\x1bReserveNotificationTypeEnum\x12.\n*RESERVE_NOTIFICATION_TYPE_ENUM_UNSPECIFIED\x10\x00\x12%\n!RESERVE_NOTIFICATION_TYPE_ENUM_OK\x10\x01\x32l\n\x0eReserveService\x12Z\n\x0bReserveItem\x12$.protos.warehouse.ReserveItemRequest\x1a%.protos.warehouse.ReserveItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reserve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVENOTIFICATIONTYPEENUM']._serialized_start=294
  _globals['_RESERVENOTIFICATIONTYPEENUM']._serialized_end=410
  _globals['_ITEM']._serialized_start=35
  _globals['_ITEM']._serialized_end=103
  _globals['_RESERVEITEMREQUEST']._serialized_start=105
  _globals['_RESERVEITEMREQUEST']._serialized_end=157
  _globals['_RESERVEITEMRESPONSE']._serialized_start=160
  _globals['_RESERVEITEMRESPONSE']._serialized_end=292
  _globals['_RESERVESERVICE']._serialized_start=412
  _globals['_RESERVESERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
