# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x0cprotos.order\"D\n\x05Order\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"C\n\x12\x43reateOrderRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"|\n\x13\x43reateOrderResponse\x12\x41\n\x10notificationType\x18\x01 \x01(\x0e\x32\'.protos.order.OrderNotificationTypeEnum\x12\"\n\x05order\x18\x02 \x01(\x0b\x32\x13.protos.order.Order*n\n\x19OrderNotificationTypeEnum\x12,\n(ORDER_NOTIFICATION_TYPE_ENUM_UNSPECIFIED\x10\x00\x12#\n\x1fORDER_NOTIFICATION_TYPE_ENUM_OK\x10\x01\x32\x62\n\x0cOrderService\x12R\n\x0b\x43reateOrder\x12 .protos.order.CreateOrderRequest\x1a!.protos.order.CreateOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERNOTIFICATIONTYPEENUM']._serialized_start=294
  _globals['_ORDERNOTIFICATIONTYPEENUM']._serialized_end=404
  _globals['_ORDER']._serialized_start=29
  _globals['_ORDER']._serialized_end=97
  _globals['_CREATEORDERREQUEST']._serialized_start=99
  _globals['_CREATEORDERREQUEST']._serialized_end=166
  _globals['_CREATEORDERRESPONSE']._serialized_start=168
  _globals['_CREATEORDERRESPONSE']._serialized_end=292
  _globals['_ORDERSERVICE']._serialized_start=406
  _globals['_ORDERSERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
