# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loyalty.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'loyalty.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rloyalty.proto\x12\x10protos.loyalties\"(\n\x07Loyalty\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07persent\x18\x02 \x01(\r\"0\n\x0eLoyaltyRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\r\"\x86\x01\n\x0fLoyaltyResponse\x12G\n\x10notificationType\x18\x01 \x01(\x0e\x32-.protos.loyalties.LoyaltyNotificationTypeEnum\x12*\n\x07loyalty\x18\x02 \x01(\x0b\x32\x19.protos.loyalties.Loyalty*t\n\x1bLoyaltyNotificationTypeEnum\x12.\n*LOYALTY_NOTIFICATION_TYPE_ENUM_UNSPECIFIED\x10\x00\x12%\n!LOYALTY_NOTIFICATION_TYPE_ENUM_OK\x10\x01\x32\x64\n\x0eLoyaltyService\x12R\n\x0bLoyaltyInfo\x12 .protos.loyalties.LoyaltyRequest\x1a!.protos.loyalties.LoyaltyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loyalty_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOYALTYNOTIFICATIONTYPEENUM']._serialized_start=264
  _globals['_LOYALTYNOTIFICATIONTYPEENUM']._serialized_end=380
  _globals['_LOYALTY']._serialized_start=35
  _globals['_LOYALTY']._serialized_end=75
  _globals['_LOYALTYREQUEST']._serialized_start=77
  _globals['_LOYALTYREQUEST']._serialized_end=125
  _globals['_LOYALTYRESPONSE']._serialized_start=128
  _globals['_LOYALTYRESPONSE']._serialized_end=262
  _globals['_LOYALTYSERVICE']._serialized_start=382
  _globals['_LOYALTYSERVICE']._serialized_end=482
# @@protoc_insertion_point(module_scope)
